CarDealership/GuildCars/GuildCars.UI/Models/AccountViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GuildCars.UI.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class ExternalLoginListViewModel
    {
        public string ReturnUrl { get; set; }
    }

    public class SendCodeViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
        public string ReturnUrl { get; set; }
        public bool RememberMe { get; set; }
    }

    public class VerifyCodeViewModel
    {
        [Required]
        public string Provider { get; set; }

        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }
        public string ReturnUrl { get; set; }

        [Display(Name = "Remember this browser?")]
        public bool RememberBrowser { get; set; }

        public bool RememberMe { get; set; }
    }

    public class ForgotViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ResetPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        public string Code { get; set; }
    }

    public class ForgotPasswordViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

CarDealership/GuildCars/GuildCars.UI/Models/AdminMakesViewModel.cs
using GuildCars.Data.Factory;
using GuildCars.Models.Table;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GuildCars.UI.Models
{
    public class AdminMakesViewModel : IValidatableObject
    {
        public List<Make> Makes { get; set; }
        public Make MakeToCreate { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (string.IsNullOrEmpty(MakeToCreate.MakeName))
            {
                errors.Add(new ValidationResult("New Make is required"));
            }
            else if (MakeToCreate.MakeName.Length > 10)
            {
                errors.Add(new ValidationResult("The max length for New Make is 10 characters"));
            }

            var repo = MakeRepositoryFactory.GetRepository();
            var makes = repo.GetAll();
            var alreadyExists = makes.Where(m=> m.MakeName.IndexOf(MakeToCreate.MakeName, StringComparison.OrdinalIgnoreCase) >= 0).ToList();

            if (alreadyExists.Count != 0)
            {
                errors.Add(new ValidationResult("That Make already exists"));
            }

            return errors;
        }
    }
}

CarDealership/GuildCars/GuildCars.UI/Controllers/AdminController.cs
using GuildCars.Data.Factory;
using GuildCars.Data.Repository.SupportData;
using GuildCars.Models.Table;
using GuildCars.UI.Models;
using GuildCars.UI.Models.Identity;
using GuildCars.UI.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security.DataProtection;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class AdminController : Controller
    {
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        public ActionResult Vehicles()
        {
            var model = new InventoryNewUsedViewModel();

            var vehicleRepo = VehicleRepositoryFactory.GetRepository();
            model.SearchVehicleRequestItem = vehicleRepo.GetAllToSell();

            var yearsRepo = new YearsRepositorySupport();
            model.Years = yearsRepo.GetAll();

            var pricesRepo = new PricesRepositorySupport();
            model.Prices = pricesRepo.GetAll();

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Users()
        {
            var repo = UserRepositoryFactory.GetRepository();
            var model = repo.GetAll();
            
            return View(model);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Makes()
        {
            var model = new AdminMakesViewModel();

            var repo = MakeRepositoryFactory.GetRepository();
            model.Makes = repo.GetAll();

            model.MakeToCreate = new Make();

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Makes(AdminMakesViewModel model)
        {

            var repo = MakeRepositoryFactory.GetRepository();

            if (ModelState.IsValid)
            {
                var make = new Make();
                var user = AuthorizeUtilities.GetUserId(this);

                make.MakeName = model.MakeToCreate.MakeName;
                make.DateAdded = DateTime.Now;
                make.AddedByUser = user;

                repo.CreateMake(make);

                return RedirectToAction("Makes");
            }
            
            model = new AdminMakesViewModel();

            model.Makes = repo.GetAll();

            model.MakeToCreate = new Make();

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Models()
        {
            var model = new AdminModelsViewModel();

            var makeRepo = MakeRepositoryFactory.GetRepository();
            model.Makes = new SelectList(makeRepo.GetAll(), "MakeName", "MakeName");
            model.MakesToQuery = makeRepo.GetAll();

            var modelRepo = ModelRepositoryFactory.GetRepository();
            model.Models = modelRepo.GetAll();

            model.ModelToCreate = new Model();

            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Models(AdminModelsViewModel model)
        {
            var makeRepo = MakeRepositoryFactory.GetRepository();
            var modelRepo = ModelRepositoryFactory.GetRepository();

            if (ModelState.IsValid)
            {
                var carModel = new Model();
                var user = AuthorizeUtilities.GetUserId(this);
                var make = makeRepo.GetAll().FirstOrDefault(m => m.MakeName == model.MakeName);

                carModel.ModelName = model.ModelToCreate.ModelName;
                carModel.MakeId = make.MakeId;
                carModel.DateAdded = DateTime.Now;
                carModel.AddedByUser = user;

                modelRepo.CreateModel(carModel);

                return RedirectToAction("Models");
            }

            model = new AdminModelsViewModel();
            
            model.Makes = new SelectList(makeRepo.GetAll(), "MakeName", "MakeName");
            model.MakesToQuery = makeRepo.GetAll();

            model.Models = modelRepo.GetAll();

            model.ModelToCreate = new Model();

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Specials()
        {
            var model = new AdminSpecialsViewModel();

            var repo = SpecialRepositoryFactory.GetRepository();
            model.Specials = repo.GetAll();

            model.FileNameForPicture = ImageUtilities.GetCurrentPictureForSpecial();
            model.FileNameForIcon = ImageUtilities.GetCurrentIconForSpecial();
            
            return View(model);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public ActionResult Specials(AdminSpecialsViewModel model)
        {
            var repo = SpecialRepositoryFactory.GetRepository();

            if (ModelState.IsValid)
            {
                var special = new Special();

                special.SpecialTitle = model.SpecialTitle;
                special.Description = model.SpecialDescription;

                repo.CreateSpecial(special);

                return RedirectToAction("Specials");
            }

            model = new AdminSpecialsViewModel();

            model.Specials = repo.GetAll();

            model.FileNameForPicture = ImageUtilities.GetCurrentPictureForSpecial();
            model.FileNameForIcon = ImageUtilities.GetCurrentIconForSpecial();

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public ActionResult AddVehicle()
        {
            var model = new AdminAddEditVehicleViewModel();

            var makesRepo = MakeRepositoryFactory.GetRepository();
            model.Makes = new SelectList(makesRepo.GetAll(), "MakeName", "MakeName");

            var modelsRepo = ModelRepositoryFactory.GetRepository();
            model.Models = new SelectList(modelsRepo.GetAll(), "ModelName", "ModelName");

            var typesRepo = TypeRepositoryFactory.GetRepository();
            model.Types = new SelectList(typesRepo.GetAll(), "TypeName", "TypeName");

            var bodyStylesRepo = BodyStyleRepositoryFactory.GetRepository();
            model.BodyStyles = new SelectList(bodyStylesRepo.GetAll(), "BodyStyleName", "BodyStyleName");

            var transRepo = TransRepositoryFactory.GetRepository();
            model.Trans = new SelectList(transRepo.GetAll(), "TransName", "TransName");

            var colorExRepo = ColorExRepositoryFactory.GetRepository();
            model.ColorEx = new SelectList(colorExRepo.GetAll(), "ColorExName", "ColorExName");

            var colorIntRepo = ColorIntRepositoryFactory.GetRepository();
            model.ColorInt = new SelectList(colorIntRepo.GetAll(), "ColorIntName", "ColorIntName");

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public ActionResult AddVehicle(AdminAddEditVehicleViewModel model)
        {
            var makesRepo = MakeRepositoryFactory.GetRepository();
            var modelsRepo = ModelRepositoryFactory.GetRepository();
            var typesRepo = TypeRepositoryFactory.GetRepository();
            var bodyStylesRepo = BodyStyleRepositoryFactory.GetRepository();
            var transRepo = TransRepositoryFactory.GetRepository();
            var colorExRepo = ColorExRepositoryFactory.GetRepository();
            var colorIntRepo = ColorIntRepositoryFactory.GetRepository();

            if (ModelState.IsValid)
            {
                var vehicle = new Vehicle();

                var make = makesRepo.GetAll().FirstOrDefault(m => m.MakeName == model.AddEditVehicleRequestItem.MakeName);
                vehicle.MakeId = make.MakeId;

                var modelToAdd = modelsRepo.GetAll().FirstOrDefault(m => m.ModelName == model.AddEditVehicleRequestItem.ModelName);
                vehicle.ModelId = modelToAdd.ModelId;

                var type = typesRepo.GetAll().FirstOrDefault(m => m.TypeName == model.AddEditVehicleRequestItem.TypeName);
                vehicle.TypeId = type.TypeId;

                var bodyStyle = bodyStylesRepo.GetAll().FirstOrDefault(m => m.BodyStyleName == model.AddEditVehicleRequestItem.BodyStyleName);
                vehicle.BodyStyleId = bodyStyle.BodyStyleId;

                var year = new DateTime(model.Year, 01, 01, 00, 00, 00);
                vehicle.Year = year;

                var trans = transRepo.GetAll().FirstOrDefault(m => m.TransName == model.AddEditVehicleRequestItem.TransName);
                vehicle.TransId = trans.TransId;

                var colorEx = colorExRepo.GetAll().FirstOrDefault(m => m.ColorExName == model.AddEditVehicleRequestItem.ColorExName);
                vehicle.ColorExId = colorEx.ColorExId;

                var colorInt = colorIntRepo.GetAll().FirstOrDefault(m => m.ColorIntName == model.AddEditVehicleRequestItem.ColorIntName);
                vehicle.ColorIntId = colorInt.ColorIntId;

                vehicle.Mileage = model.AddEditVehicleRequestItem.Mileage;
                vehicle.VIN = model.AddEditVehicleRequestItem.VIN;
                vehicle.MSRP = model.AddEditVehicleRequestItem.MSRP;
                vehicle.SalePrice = model.AddEditVehicleRequestItem.SalePrice;
                vehicle.Description = model.AddEditVehicleRequestItem.Description;

                var vehicles = VehicleRepositoryFactory.GetRepository();
                var inventoryNumber = vehicles.GetAll().Max(m=>m.VehicleId) + 1;
                var fileName = "inventory-" + inventoryNumber;

                var savePath = Server.MapPath("~/ImagesPROD");
                string extension = Path.GetExtension(model.PictureUpload.FileName);
                var filePath = Path.Combine(savePath, fileName + extension);
                model.PictureUpload.SaveAs(filePath);

CarDealership/GuildCars/GuildCars.UI/Controllers/InventoryController.cs
using GuildCars.Data.Factory;
using GuildCars.Data.Repository.SupportData;
using GuildCars.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace GuildCars.UI.Controllers
{
    public class InventoryController : Controller
    {
        public ActionResult New()
        {
            var model = new InventoryNewUsedViewModel();

            var vehicleRepo = VehicleRepositoryFactory.GetRepository();
            model.SearchVehicleRequestItem = vehicleRepo.GetAllNew();

            var yearsRepo = new YearsRepositorySupport();
            model.Years = yearsRepo.GetAll();

            var pricesRepo = new PricesRepositorySupport();
            model.Prices = pricesRepo.GetAll();

            return View(model);
        }

        public ActionResult Used()
        {
            var model = new InventoryNewUsedViewModel();

            var vehicleRepo = VehicleRepositoryFactory.GetRepository();
            model.SearchVehicleRequestItem = vehicleRepo.GetAllUsed();

            var yearsRepo = new YearsRepositorySupport();
            model.Years = yearsRepo.GetAll();

            var pricesRepo = new PricesRepositorySupport();
            model.Prices = pricesRepo.GetAll();

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var repo = VehicleRepositoryFactory.GetRepository();
            var model = repo.SearchVehicleById(id);

            var vehicles = repo.GetAll();

            if (id > vehicles.Max(m => m.VehicleId))
            {
                return RedirectToAction("Index", "Home");
            }

            TempData["vinMessage"] = "Hello, I am interested in VIN#: " + model.VIN + ". Please contact me.";

            return View(model);
        }
    }
}

CarDealership/GuildCars/GuildCars.UI/Controllers/ReportsController.cs
using GuildCars.Data.Factory;
using GuildCars.Data.Repository.SupportData;
using GuildCars.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GuildCars.UI.Controllers
{
    public class ReportsController : Controller
    {
        [Authorize(Roles = "admin")]
        public ActionResult Inventory()
        {
            var model = new ReportsInventoryViewModel();
            
            var repo = VehicleRepositoryFactory.GetRepository();
            model.NewInventory = repo.AdminGetNewInventoryReport();
            model.UsedInventory = repo.AdminGetUsedInventoryReport();

            return View(model);
        }

        [Authorize(Roles = "admin")]
        public ActionResult Sales()
        {
            var model = new ReportsSalesViewModel();

            var saleRepo = SaleRepositoryFactory.GetRepository();
            model.SalesReportRequestItem = saleRepo.GetSalesReport();

            model.Users = new List<string>();
            foreach(var user in model.SalesReportRequestItem)
            {
                model.Users.Add(user.FirstName + " " + user.LastName);
            }

            var yearsRepo = new YearsRepositorySupport();
            model.Years = yearsRepo.GetAllSales();

            return View(model);
        }
    }
}

CarDealership/GuildCars/GuildCars.UI/Views/Admin/AddUser.cshtml
@model GuildCars.UI.Models.AdminAddUserViewModel
@{
    ViewBag.Title = "Admin - Add User";
}
<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-12">
            <h1>Add User</h1>
        </div>
    </div>
    <div class="row">
        @using (Html.BeginForm("AddUser", "Admin", FormMethod.Post, new { id = "formAddUser" }))
        {
            @Html.ValidationSummary()
            <div class="col-xs-12">
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>First Name</label>
                            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>Last Name</label>
                            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>Email</label>
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-2 col-md-2">
                        <div class="form-group">
                            <label>Role</label>
                            @Html.DropDownListFor(m => m.Role, Model.Roles, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>Password</label>
                            @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>Confirm Password</label>
                            @Html.TextBoxFor(m => m.ConfirmPassword, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <button class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('#formAddUser').validate({
                rules: {
                    'FirstName': {
                        required: true,
                        minlength: 1,
                        maxlength: 50
                    },
                    'LastName': {
                        required: true,
                        minlength: 1,
                        maxlength: 50
                    },
                    'Email': {
                        required: true,
                        email: true,
                        minlength: 17,
                        maxlength: 50
                    },
                    'Role': {
                        required: true
                    },
                    'Password': {
                        required: true,
                        minlength: 6,
                        maxlength: 30
                    },
                    'ConfirmPassword': {
                        required: true,
                        equalTo: '#Password'
                    }
                }
            })
        })
    </script>
}

CarDealership/GuildCars/GuildCars.UI/Views/Admin/EditUser.cshtml
@model GuildCars.UI.Models.AdminEditUserViewModel
@{
    ViewBag.Title = "Admin - Edit User";
}
<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-12">
            <h1>Edit User</h1>
        </div>
    </div>
    <div class="row">
        @using (Html.BeginForm("EditUser", "Admin", FormMethod.Post, new { id = "formEditUser" }))
        {
            @Html.ValidationSummary()
            @Html.HiddenFor(m=>m.Id)
            <div class="col-xs-12">
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>First Name</label>
                            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>Last Name</label>
                            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>Email</label>
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-2 col-md-2">
                        <div class="form-group">
                            <label>Role</label>
                            @Html.DropDownListFor(m => m.Role, Model.Roles, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>Password</label>
                            @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <div class="form-group">
                            <label>Confirm Password</label>
                            @Html.TextBoxFor(m => m.ConfirmPassword, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-4 col-md-4">
                        <button class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('#formEditUser').validate({
                rules: {
                    'FirstName': {
                        required: true,
                        minlength: 1,
                        maxlength: 50
                    },
                    'LastName': {
                        required: true,
                        minlength: 1,
                        maxlength: 50
                    },
                    'Email': {
                        required: true,
                        email: true,
                        minlength: 17,
                        maxlength: 50
                    },
                    'Role': {
                        required: true
                    },
                    'Password': {
                        minlength: 6,
                        maxlength: 30
                    },
                    'ConfirmPassword': {
                        equalTo: '#Password'
                    }
                }
            })
        })
    </script>
}

CarDealership/GuildCars/GuildCars.UI/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin - Index";
}

<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-12">
            <h1>Admin Routes</h1>
        </div>
    </div>
    <div class="row" >
        <div class="col-xs-12 col-sm-3 col-md-3">
            <hr />
            <h4>@Html.ActionLink("Vehicles", "Vehicles", "Admin")</h4>
            <hr />
            <h4>@Html.ActionLink("Users", "Users", "Admin")</h4>
            <hr />
            <h4>@Html.ActionLink("Makes", "Makes", "Admin")</h4>
            <hr />
            <h4>@Html.ActionLink("Models", "Models", "Admin")</h4>
            <hr />
            <h4>@Html.ActionLink("Specials", "Specials", "Admin")</h4>
            <hr />
            <h4>@Html.ActionLink("Sales Report", "Sales", "Reports")</h4>
            <hr />
            <h4>@Html.ActionLink("Inventory Report", "Inventory", "Reports")</h4>
        </div>
    </div>
</div>

CarDealership/GuildCars/GuildCars.UI/Views/Admin/Makes.cshtml
@model GuildCars.UI.Models.AdminMakesViewModel
@{
    ViewBag.Title = "Admin - Makes";
}

<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-12">
            <h1>Makes</h1>
        </div>
    </div>
    <div class="row" id="styleBorder">
        @using (Html.BeginForm("Makes", "Admin", FormMethod.Post, new { id = "formAddMake" }))
        {
            @Html.ValidationSummary()
            <div class="col-xs-4">
                <div class="form-group form-inline">
                    <label style="display:inline">New Make </label>
                    @Html.TextBoxFor(m => m.MakeToCreate.MakeName, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-xs-1">
                <div class="form-group form-inline">
                    <button class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
    <br />
    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4" id="styleBorder">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Make</th>
                        <th>Date Added</th>
                        <th>User</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var make in Model.Makes)
                    {
                        <tr>
                            <td>@make.MakeName</td>
                            <td>@make.DateAdded.Month/@make.DateAdded.Day/@make.DateAdded.Year</td>
                            <td>@make.AddedByUser</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('#formAddMake').validate({
                rules: {
                    'MakeToCreate.MakeName': {
                        required: true,
                        maxlength: 10
                    }
                }
            })
        })
    </script>
}

CarDealership/GuildCars/GuildCars.UI/Views/Admin/Models.cshtml
@model GuildCars.UI.Models.AdminModelsViewModel
@{
    ViewBag.Title = "Admin - Models";
}

<div class="col-xs-12">
    <div class="row">
        <div class="col-xs-12">
            <h1>Models</h1>
        </div>
    </div>
    <div class="row" id="styleBorder">
        @using (Html.BeginForm("Models", "Admin", FormMethod.Post, new { id = "formAddModel" }))
        {
            @Html.ValidationSummary()
            <div class="col-xs-4">
                <div class="form-group form-inline">
                    <label style="display:inline">New Model </label>
                    @Html.TextBoxFor(m => m.ModelToCreate.ModelName, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-xs-2">
                <div class="form-group form-inline">
                    <label style="display:inline">Make </label>
                    @Html.DropDownListFor(m => m.MakeName, Model.Makes, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-xs-1">
                <div class="form-group form-inline">
                    <button class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
    <br />
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6" id="styleBorder">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Make</th>
                        <th>Model</th>
                        <th>Date Added</th>
                        <th>User</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var carModel in Model.Models)
                    {
                        <tr>
                            <td>@carModel.ModelName</td>
                            @foreach (var make in Model.MakesToQuery)
                            {
                                if (make.MakeId == carModel.MakeId)
                                {
                                    <td>@make.MakeName</td>
                                }
                            }
                            <td>@carModel.DateAdded.Month/@carModel.DateAdded.Day/@carModel.DateAdded.Year</td>
                            <td>@carModel.AddedByUser</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('#formAddModel').validate({
                rules: {
                    'ModelToCreate.ModelName': {
                        required: true,
                        maxlength: 20
                    }
                }
            })
        })
    </script>
}